"""fk post author id and ondelete post tags table

Revision ID: 3c8d3137eacf
Revises: 81b2a74aec53
Create Date: 2024-04-05 17:36:27.330586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c8d3137eacf'
down_revision = '81b2a74aec53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('fk_post_author_id_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_post_author_id_user'), 'user', ['author_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('post_tags', schema=None) as batch_op:
        batch_op.alter_column('post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('tag_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint(batch_op.f('uq_post_tags_post_id'), ['post_id', 'tag_id'])
        batch_op.drop_constraint('fk_post_tags_post_id_post', type_='foreignkey')
        batch_op.drop_constraint('fk_post_tags_tag_id_tag', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_post_tags_tag_id_tag'), 'tag', ['tag_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_post_tags_post_id_post'), 'post', ['post_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_tags', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_post_tags_post_id_post'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_post_tags_tag_id_tag'), type_='foreignkey')
        batch_op.create_foreign_key('fk_post_tags_tag_id_tag', 'tag', ['tag_id'], ['id'])
        batch_op.create_foreign_key('fk_post_tags_post_id_post', 'post', ['post_id'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_post_tags_post_id'), type_='unique')
        batch_op.alter_column('tag_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('post_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_post_author_id_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_post_author_id_user', 'user', ['author_id'], ['id'])

    # ### end Alembic commands ###
